# Generated by Django 5.0 on 2023-12-29 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auction', '0001_initial'),
        ('lot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction', to='lot.lot'),
        ),
    ]
