# Generated by Django 5.0 on 2023-12-22 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auction', '0001_initial'),
        ('lot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionsmodel',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='lot.lotmodel'),
        ),
    ]
