# Generated by Django 5.0 on 2023-12-22 17:42

import apps.lot.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Audi', max_length=128)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Red', max_length=128)),
            ],
            options={
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='ConditionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Low Damage', max_length=128)),
            ],
            options={
                'db_table': 'condition',
            },
        ),
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='1.3L 4', max_length=128)),
            ],
            options={
                'db_table': 'engine',
            },
        ),
        migrations.CreateModel(
            name='FuelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Diesel', max_length=128)),
            ],
            options={
                'db_table': 'fuel',
            },
        ),
        migrations.CreateModel(
            name='ModelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='X9', max_length=128)),
            ],
            options={
                'db_table': 'model',
            },
        ),
        migrations.CreateModel(
            name='PhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'photo',
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Automobiles', max_length=128)),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
        migrations.CreateModel(
            name='LotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('year', models.IntegerField(default=2022)),
                ('odometer', models.IntegerField(default=220000)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='lot.colormodel')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='lot.conditionmodel')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='lot.enginemodel')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='lot.fuelmodel')),
                ('comment', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('draft', apps.lot.models.StateEnum['Draft']), ('active', apps.lot.models.StateEnum['Active']), ('closed', apps.lot.models.StateEnum['Closed'])], default='draft', max_length=10)),
            ],
            options={
                'db_table': 'lot',
            },
        ),
    ]
