# Generated by Django 5.0 on 2023-12-22 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lotmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelmodel',
            name='brande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='lot.brandmodel'),
        ),
        migrations.AddField(
            model_name='lotmodel',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='lot.modelmodel'),
        ),
        migrations.AddField(
            model_name='photomodel',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='lot.lotmodel'),
        ),
        migrations.AddField(
            model_name='lotmodel',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='lot.vehiclemodel'),
        ),
    ]
