# Generated by Django 5.0 on 2024-01-02 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='model',
            name='brande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='lot.brand'),
        ),
        migrations.AddField(
            model_name='lot',
            name='model',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='lot.model'),
        ),
        migrations.AddField(
            model_name='photo',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='lot.lot'),
        ),
        migrations.AddField(
            model_name='lot',
            name='vehicle',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='lot.vehicle'),
        ),
    ]
