# Generated by Django 5.0 on 2023-12-29 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bet', models.BigIntegerField(verbose_name='bet')),
                ('auction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_auction', to='auction.auction', verbose_name='auction')),
            ],
            options={
                'verbose_name': 'bid',
                'verbose_name_plural': 'bids',
            },
        ),
    ]
